"""adding message type

Revision ID: 90f40efba2e0
Revises: 7bd3db5a96d1
Create Date: 2023-04-07 10:49:22.113964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f40efba2e0'
down_revision = '7bd3db5a96d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.Enum('SYSTEM', 'AI', 'USER', name='messagetype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###
